title: Make an Initial State dashboard for weather data
hero_image: images/banner.png
description: make-an-initial-state-dashboard-for-weather-data
original_url:
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator
interests: "nature/outside/weather"
technologies: "web, sense-hat, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Registering with Initial State
  - title: Uploading data to Initial State
  - title: Using Live data
  - title: Visualising your data
  - title: Challenge
